# Generated by Django 5.1 on 2024-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('district', models.CharField(choices=[('Kailahun', 'Kailahun'), ('Kenema', 'Kenema'), ('Kono', 'Kono'), ('Bombali', 'Bombali'), ('Falaba', 'Falaba'), ('Koinadugu', 'Koinadugu'), ('Tonkolili', 'Tonkolili'), ('Kambia', 'Kambia'), ('Karene', 'Karene'), ('Port Loko', 'Port Loko'), ('Bo', 'Bo'), ('Bonthe', 'Bonthe'), ('Moyamba', 'Moyamba'), ('Pujehun', 'Pujehun'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Western Urban')], max_length=100)),
                ('pin_code', models.CharField(max_length=20, unique=True)),
                ('subjects_taught', models.TextField(help_text='List of subjects separated by commas')),
                ('schools_taught', models.TextField(help_text='List of subjects separated by commas')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
