# Generated by Django 5.1 on 2024-11-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='province',
            field=models.CharField(choices=[('Eastern', 'Eastern'), ('Northern', 'Northern'), ('Southern', 'Southern'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Western Urban')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
