# Generated by Django 5.1 on 2024-11-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_admi_salary_budget_admin_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='on_the_job_traninig',
            new_name='on_the_job_training',
        ),
    ]
