# Generated by Django 5.1 on 2024-11-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_on_the_job_traninig_budget_on_the_job_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='time_of_service',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
