# Generated by Django 5.1 on 2024-11-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_budget_time_of_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='time_of_service',
        ),
        migrations.AddField(
            model_name='teacher',
            name='time_of_service',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
