# Generated by Django 5.1 on 2024-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_budget_time_of_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateField()),
                ('message_subject', models.CharField(max_length=300)),
                ('message_body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='President_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateField()),
                ('message_subject', models.CharField(max_length=300)),
                ('message_body', models.CharField(max_length=1000)),
            ],
        ),
    ]
