# Generated by Django 5.1 on 2024-11-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_finance_message_president_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrative_Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('budget_date', models.DateField()),
                ('executive_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leave_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acting_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_the_job_training', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paye_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('audit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internal_transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('light_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_affiliate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('payment_date', models.DateField()),
                ('expenditure_type', models.CharField(max_length=200)),
                ('staff_position', models.CharField(max_length=120)),
                ('payment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Welfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('budget_date', models.DateField()),
            ],
        ),
    ]
