# Generated by Django 5.1 on 2024-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_administrative_budget_salary_allowance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statutory_Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('payment_date', models.DateField()),
                ('deduction_type', models.CharField(max_length=200)),
                ('staff_position', models.CharField(max_length=120)),
                ('payment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
