# Generated by Django 5.1 on 2024-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_statutory_deduction_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Running_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('deduction_type', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
